export const codeLanguages = [
  ["", "Auto detect"],
  ["plaintext", "Plain text"],
  ["bash", "Bash"],
  ["sh", "Shell (sh)"],
  ["c", "C"],
  ["cpp", "C++"],
  ["csharp", "C#"],
  ["css", "CSS"],
  ["diff", "Diff"],
  ["go", "Go"],
  ["graphql", "GraphQL"],
  ["html", "HTML"],
  ["xml", "XML"],
  ["java", "Java"],
  ["js", "JavaScript (js)"],
  ["javascript", "JavaScript"],
  ["json", "JSON"],
  ["kotlin", "Kotlin"],
  ["lua", "Lua"],
  ["makefile", "Makefile"],
  ["markdown", "Markdown"],
  ["php", "PHP"],
  ["python", "Python"],
  ["r", "R"],
  ["ruby", "Ruby"],
  ["rust", "Rust"],
  ["sql", "SQL"],
  ["swift", "Swift"],
  ["ts", "TypeScript (ts)"],
  ["typescript", "TypeScript"],
  ["yaml", "YAML"],
] as const;
